name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  clippy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check cargofmt
        run: cargo fmt -- --check

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
